version: "3"
services:
  test:
    build: .
    ports:
      - "3025:3025"
    container_name: adapter-gfw
    # env_file:
      # - dev.env
    environment:
      PORT: 3025
      NODE_PATH: app/src
      GATEWAY_URL: http://mymachine:9000
      MICROSERVICE_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Im1pY3Jvc2VydmljZSIsImNyZWF0ZWRBdCI6IjIwMTYtMDktMTQifQ.IRCIRm1nfIQTfda_Wb6Pg-341zhV8soAgzw7dd5HxxQ
      FASTLY_ENABLED: "false"
    command: develop
    volumes:
      - ./app:/opt/adapter-gfw/app
