version: "3"
services:
  test:
    build: .
    ports:
      - "3025"
    container_name: rw-adapter-gfw-test
    environment:
      NODE_ENV: test
      GATEWAY_URL: http://mymachine:9000
      MICROSERVICE_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Im1pY3Jvc2VydmljZSIsImNyZWF0ZWRBdCI6IjIwMTYtMDktMTQifQ.IRCIRm1nfIQTfda_Wb6Pg-341zhV8soAgzw7dd5HxxQ
      GFW_API_KEY: 'fake-key'
      FASTLY_ENABLED: "false"
      AWS_REGION: "us-east-1"
      AWS_ACCESS_KEY_ID: "test"
      AWS_SECRET_ACCESS_KEY: "test"
      REQUIRE_API_KEY: true
    command: test
